name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5.6.0
        with:
          java-version: "17"
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Install NDK 29 for proot native build
        run: sdkmanager "ndk;29.0.13846066" "cmake;3.22.1"

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Fix gradle.properties for CI
        run: sed -i '/android\.aapt2FromMavenOverride/d' gradle.properties

      - name: Build unsigned release APK
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Alpiner-unsigned
          path: app/build/outputs/apk/release/*.apk
